class KenyaCounty {
  const KenyaCounty({required this.code, required this.name});

  final String code;
  final String name;
}

const kenyaCounties = <KenyaCounty>[
  KenyaCounty(code: '001', name: 'Mombasa'),
  KenyaCounty(code: '002', name: 'Kwale'),
  KenyaCounty(code: '003', name: 'Kilifi'),
  KenyaCounty(code: '004', name: 'Tana River'),
  KenyaCounty(code: '005', name: 'Lamu'),
  KenyaCounty(code: '006', name: 'Taita Taveta'),
  KenyaCounty(code: '007', name: 'Garissa'),
  KenyaCounty(code: '008', name: 'Wajir'),
  KenyaCounty(code: '009', name: 'Mandera'),
  KenyaCounty(code: '010', name: 'Marsabit'),
  KenyaCounty(code: '011', name: 'Isiolo'),
  KenyaCounty(code: '012', name: 'Meru'),
  KenyaCounty(code: '013', name: 'Tharaka-Nithi'),
  KenyaCounty(code: '014', name: 'Embu'),
  KenyaCounty(code: '015', name: 'Kitui'),
  KenyaCounty(code: '016', name: 'Machakos'),
  KenyaCounty(code: '017', name: 'Makueni'),
  KenyaCounty(code: '018', name: 'Nyandarua'),
  KenyaCounty(code: '019', name: 'Nyeri'),
  KenyaCounty(code: '020', name: 'Kirinyaga'),
  KenyaCounty(code: '021', name: 'Murang\'a'),
  KenyaCounty(code: '022', name: 'Kiambu'),
  KenyaCounty(code: '023', name: 'Turkana'),
  KenyaCounty(code: '024', name: 'West Pokot'),
  KenyaCounty(code: '025', name: 'Samburu'),
  KenyaCounty(code: '026', name: 'Trans Nzoia'),
  KenyaCounty(code: '027', name: 'Uasin Gishu'),
  KenyaCounty(code: '028', name: 'Elgeyo-Marakwet'),
  KenyaCounty(code: '029', name: 'Nandi'),
  KenyaCounty(code: '030', name: 'Baringo'),
  KenyaCounty(code: '031', name: 'Laikipia'),
  KenyaCounty(code: '032', name: 'Nakuru'),
  KenyaCounty(code: '033', name: 'Narok'),
  KenyaCounty(code: '034', name: 'Kajiado'),
  KenyaCounty(code: '035', name: 'Kericho'),
  KenyaCounty(code: '036', name: 'Bomet'),
  KenyaCounty(code: '037', name: 'Kakamega'),
  KenyaCounty(code: '038', name: 'Vihiga'),
  KenyaCounty(code: '039', name: 'Bungoma'),
  KenyaCounty(code: '040', name: 'Busia'),
  KenyaCounty(code: '041', name: 'Siaya'),
  KenyaCounty(code: '042', name: 'Kisumu'),
  KenyaCounty(code: '043', name: 'Homa Bay'),
  KenyaCounty(code: '044', name: 'Migori'),
  KenyaCounty(code: '045', name: 'Kisii'),
  KenyaCounty(code: '046', name: 'Nyamira'),
  KenyaCounty(code: '047', name: 'Nairobi'),
];
